run:
  timeout: 5m
  go: "1.21"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - typecheck

linters-settings:
  errcheck:
    check-blank: false
  staticcheck:
    checks: ["all", "-SA1019"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
